export const styleDatas = [
    { label: "Blues", value: "blues" },
    { label: "B.O", value: "bo" },
    { label: "Chanson", value: "song" },
    { label: "Classique", value: "classical" },
    { label: "Country", value: "country" },
    { label: "Electro", value: "electro" },
    { label: "Folk", value: "folk" },
    { label: "Funk", value: "funk" },
    { label: "Hip-Hop", value: "hip_hop" },
    { label: "Jazz", value: "jazz" },
    { label: "Latin", value: "latin" },
    { label: "Métal", value: "metal" },
    { label: "Pop", value: "pop" },
    { label: "Reggae", value: "reggae" },
    { label: "Rock", value: "rock" },
    { label: "Soul", value: "soul" },
    { label: "World", value: "world" },
    { label: "Autres", value: "other" },
]